version: "3.9"

services:
    adihara-py-boilerplate:
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
            - HASH_SALT=${HASH_SALT}
        build: .
        command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
        ports:
            - "${APP_PORT:-3000}:3000"